#!/usr/bin/env python3
"""
Backtest template for XLSX files generated by resample_klines_to_excel.py.

Strategy (long-only):
1) Regime filter: prob_up >= prob_threshold
2) Momentum entry: direction == up and roi_x_minute > 0
3) Flow confirmation: taker_buy_base_volume / volume >= min_taker_ratio
4) Overextension filter: roi_x_minute <= max_roi_entry
5) Exit by stop-loss, take-profit, or loss of edge
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd


@dataclass
class Position:
    entry_idx: int
    entry_time: str
    entry_price: float
    qty: float
    stop_price: float
    take_price: float
    fees_paid: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Backtest template on XLSX candles.")
    parser.add_argument("--input", required=True, help="Path to input XLSX file.")
    parser.add_argument(
        "--sheet", default="5min", help="Sheet to backtest, e.g. 5min, 15min."
    )
    parser.add_argument(
        "--initial-capital", type=float, default=10_000.0, help="Initial capital."
    )
    parser.add_argument(
        "--fee-bps",
        type=float,
        default=5.0,
        help="Fee in basis points per side (e.g. 5 = 0.05%%).",
    )
    parser.add_argument(
        "--risk-per-trade",
        type=float,
        default=0.01,
        help="Fraction of equity risked per trade (e.g. 0.01 = 1%%).",
    )
    parser.add_argument(
        "--prob-threshold",
        type=float,
        default=0.60,
        help="Entry threshold for prob_up.",
    )
    parser.add_argument(
        "--exit-prob-threshold",
        type=float,
        default=0.50,
        help="Exit threshold for prob_up.",
    )
    parser.add_argument(
        "--min-taker-ratio",
        type=float,
        default=0.55,
        help="Minimum taker_buy_base_volume / volume for entry.",
    )
    parser.add_argument(
        "--max-roi-entry",
        type=float,
        default=0.012,
        help="Max roi_x_minute allowed for entry (overextension filter).",
    )
    parser.add_argument(
        "--sl-mult",
        type=float,
        default=0.8,
        help="SL multiplier over rolling volatility mean.",
    )
    parser.add_argument(
        "--tp-mult",
        type=float,
        default=1.5,
        help="TP multiplier over rolling volatility mean.",
    )
    parser.add_argument(
        "--vol-window",
        type=int,
        default=20,
        help="Rolling window for volatility reference.",
    )
    parser.add_argument(
        "--trades-output",
        default="",
        help="Optional CSV path to save trade-by-trade results.",
    )
    return parser.parse_args()


def validate_columns(df: pd.DataFrame) -> None:
    required = [
        "open_time_utc",
        "close",
        "direction",
        "roi_x_minute",
        "prob_up",
        "volatility",
        "volume",
        "taker_buy_base_volume",
    ]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns in sheet: {missing}")


def safe_div(a: pd.Series, b: pd.Series) -> pd.Series:
    out = np.zeros(len(a), dtype=float)
    mask = b.to_numpy() > 0
    out[mask] = (a.to_numpy()[mask] / b.to_numpy()[mask]).astype(float)
    return pd.Series(out, index=a.index)


def max_drawdown_pct(equity_curve: list[float]) -> float:
    if not equity_curve:
        return 0.0
    peak = equity_curve[0]
    max_dd = 0.0
    for value in equity_curve:
        if value > peak:
            peak = value
        dd = 0.0 if peak <= 0 else (peak - value) / peak
        if dd > max_dd:
            max_dd = dd
    return max_dd * 100.0


def run_backtest(args: argparse.Namespace) -> tuple[dict[str, float], pd.DataFrame]:
    df = pd.read_excel(args.input, sheet_name=args.sheet)
    validate_columns(df)
    df = df.copy()

    df["open_time_utc"] = pd.to_datetime(df["open_time_utc"], errors="coerce", utc=True)
    df = df.dropna(subset=["open_time_utc", "close"]).sort_values("open_time_utc")
    df = df.reset_index(drop=True)

    for col in [
        "close",
        "roi_x_minute",
        "prob_up",
        "volatility",
        "volume",
        "taker_buy_base_volume",
    ]:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    df = df.dropna(subset=["close", "roi_x_minute", "prob_up", "volatility"])
    df = df.reset_index(drop=True)

    df["taker_ratio"] = safe_div(df["taker_buy_base_volume"], df["volume"])
    vol_ref = (
        df["volatility"]
        .rolling(window=max(1, int(args.vol_window)), min_periods=1)
        .mean()
        .fillna(0.0)
    )
    fallback_vol = float(df["volatility"].median()) if len(df) else 0.0
    if fallback_vol <= 0:
        fallback_vol = 0.002
    vol_ref = vol_ref.where(vol_ref > 0, fallback_vol)

    fee_rate = args.fee_bps / 10_000.0
    equity = float(args.initial_capital)
    position: Position | None = None
    trades: list[dict[str, float | str]] = []
    equity_curve: list[float] = [equity]

    for idx, row in df.iterrows():
        close = float(row["close"])
        prob_up = float(row["prob_up"])
        roi = float(row["roi_x_minute"])
        direction = str(row["direction"]).strip().lower()
        vol_i = float(vol_ref.iloc[idx])
        ts = row["open_time_utc"].isoformat()

        if position is not None:
            exit_reason = ""
            if close <= position.stop_price:
                exit_reason = "stop_loss"
            elif close >= position.take_price:
                exit_reason = "take_profit"
            elif direction == "down" or prob_up < args.exit_prob_threshold:
                exit_reason = "edge_lost"

            if exit_reason:
                exit_price = close * (1.0 - fee_rate)
                exit_fee = close * position.qty * fee_rate
                pnl = (exit_price - position.entry_price) * position.qty
                equity += pnl
                trades.append(
                    {
                        "entry_time": position.entry_time,
                        "exit_time": ts,
                        "entry_price": position.entry_price,
                        "exit_price": exit_price,
                        "qty": position.qty,
                        "pnl": pnl,
                        "return_pct": (pnl / (position.entry_price * position.qty))
                        * 100.0,
                        "reason": exit_reason,
                        "fees_total": position.fees_paid + exit_fee,
                    }
                )
                position = None

        if position is None:
            entry_ok = (
                prob_up >= args.prob_threshold
                and direction == "up"
                and roi > 0
                and roi <= args.max_roi_entry
                and float(row["taker_ratio"]) >= args.min_taker_ratio
            )
            if entry_ok:
                entry_price = close * (1.0 + fee_rate)
                risk_distance = max(vol_i * args.sl_mult, 0.0005)
                stop_price = entry_price * (1.0 - risk_distance)
                take_price = entry_price * (1.0 + (vol_i * args.tp_mult))
                risk_per_unit = max(entry_price - stop_price, entry_price * 0.0005)
                risk_budget = equity * args.risk_per_trade
                qty = risk_budget / risk_per_unit if risk_per_unit > 0 else 0.0
                max_qty = equity / entry_price if entry_price > 0 else 0.0
                qty = float(max(0.0, min(qty, max_qty)))

                if qty > 0:
                    entry_fee = close * qty * fee_rate
                    position = Position(
                        entry_idx=idx,
                        entry_time=ts,
                        entry_price=entry_price,
                        qty=qty,
                        stop_price=stop_price,
                        take_price=take_price,
                        fees_paid=entry_fee,
                    )

        if position is not None:
            mark_to_market = equity + (close - position.entry_price) * position.qty
            equity_curve.append(mark_to_market)
        else:
            equity_curve.append(equity)

    if position is not None and len(df):
        last = df.iloc[-1]
        close = float(last["close"])
        ts = pd.to_datetime(last["open_time_utc"], utc=True).isoformat()
        exit_price = close * (1.0 - fee_rate)
        exit_fee = close * position.qty * fee_rate
        pnl = (exit_price - position.entry_price) * position.qty
        equity += pnl
        trades.append(
            {
                "entry_time": position.entry_time,
                "exit_time": ts,
                "entry_price": position.entry_price,
                "exit_price": exit_price,
                "qty": position.qty,
                "pnl": pnl,
                "return_pct": (pnl / (position.entry_price * position.qty)) * 100.0,
                "reason": "end_of_data",
                "fees_total": position.fees_paid + exit_fee,
            }
        )
        equity_curve.append(equity)

    trades_df = pd.DataFrame(trades)
    num_trades = int(len(trades_df))
    wins = int((trades_df["pnl"] > 0).sum()) if num_trades else 0
    losses = int((trades_df["pnl"] < 0).sum()) if num_trades else 0
    gross_profit = (
        float(trades_df.loc[trades_df["pnl"] > 0, "pnl"].sum()) if num_trades else 0.0
    )
    gross_loss = (
        float(-trades_df.loc[trades_df["pnl"] < 0, "pnl"].sum()) if num_trades else 0.0
    )

    if gross_loss > 0:
        profit_factor = gross_profit / gross_loss
    elif gross_profit > 0:
        profit_factor = float("inf")
    else:
        profit_factor = 0.0

    summary = {
        "initial_capital": float(args.initial_capital),
        "final_capital": float(equity),
        "total_return_pct": ((equity / args.initial_capital) - 1.0) * 100.0,
        "num_trades": float(num_trades),
        "win_rate": (wins / num_trades) * 100.0 if num_trades else 0.0,
        "loss_rate": (losses / num_trades) * 100.0 if num_trades else 0.0,
        "profit_factor": float(profit_factor),
        "max_drawdown_pct": max_drawdown_pct(equity_curve),
        "avg_trade_return_pct": float(trades_df["return_pct"].mean())
        if num_trades
        else 0.0,
        "avg_pnl": float(trades_df["pnl"].mean()) if num_trades else 0.0,
    }
    return summary, trades_df


def print_summary(summary: dict[str, float]) -> None:
    print("=== Backtest Summary ===")
    for key in [
        "initial_capital",
        "final_capital",
        "total_return_pct",
        "num_trades",
        "win_rate",
        "loss_rate",
        "profit_factor",
        "max_drawdown_pct",
        "avg_trade_return_pct",
        "avg_pnl",
    ]:
        value = summary[key]
        if np.isinf(value):
            printable = "inf"
        else:
            printable = f"{value:.6f}" if abs(value) < 1000 else f"{value:,.2f}"
        print(f"{key}: {printable}")


def main() -> None:
    args = parse_args()
    summary, trades_df = run_backtest(args)
    print_summary(summary)

    if args.trades_output:
        output_path = Path(args.trades_output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        trades_df.to_csv(output_path, index=False)
        print(f"Trades saved to: {output_path}")


if __name__ == "__main__":
    main()
